//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int EmpId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DOB { get; set; }
        public string Image { get; set; }
        public string aid { get; set; }
        public string dvid { get; set; }
    }
}
